FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-bullseye

RUN apt update
RUN apt install curl vim git sudo

COPY balenainstaller.sh balenainstaller.sh
RUN chmod +x ./balenainstaller.sh

CMD ./balenainstaller.sh
CMD ["bash"]